

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: TodoList_SqlExpress
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TodoSecurePassword123!
    ports:
      - "1433:1433"
    platform: linux/amd64
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
